services:
  # Metric Database
  influxdb:
    image: influxdb:2.7
    container_name: influxdb_sme
    restart: unless-stopped
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=sosreport2026
      - DOCKER_INFLUXDB_INIT_ORG=sosanalyzer
      - DOCKER_INFLUXDB_INIT_BUCKET=sar_metrics
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=local-sosreport-token-2026
    volumes:
      - influx_data:/var/lib/influxdb2

  # Log Database
  loki:
    image: grafana/loki:2.9.0
    container_name: loki_sme
    restart: unless-stopped
    user: "0"
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
      - loki_data:/data/loki

  # Dashboard
  grafana:
    image: grafana/grafana:10.4.0
    container_name: grafana_sme
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=sosreport2026
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_SERVER_SERVE_FROM_SUB_PATH=false
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  influx_data:
  loki_data:
  grafana_data: